blank_issues_enabled: false
contact_links:
  - name: Questions / 質問はこちら
    url: https://docs.google.com/forms/d/e/1FAIpQLSdIzggUtdg0N7kS4iYjv1nqnKirLQODSVr8Zz306npV1IeNIA/viewform
    about: Please use the contact form for questions about the book. / 本についてのご質問は、お問い合わせフォームからどうぞ。
